In [ ]:
import numpy as np

In [7]:
np.__version__

'1.20.1'

In [43]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
a=np.arange(0,21,1)
print(a)
b=np.linspace(0, 20, num=21,endpoint=True,retstep=False, dtype="int64")
print(b)
#2.呈上題，將以上數列取出偶數。
c=a[2:21:2]
print(c)
#3.呈1題，將數列取出3的倍數。
d=a[3:20:3]
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]
[ 3  6  9 12 15 18]
