In [12]:
import numpy as np

In [15]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
array_inv=np.linalg.inv(array1)
array_inv@array1

array([[ 1.00000000e+00, -5.55111512e-17],
       [-1.11022302e-16,  1.00000000e+00]])

In [16]:
#2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(array1)
eigenvalues=print(w)
eigenvectors=print(v)


[13.  2.]
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [17]:
#3. 運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)
u=print(u)
s=print(s)
vh=print(vh)

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
[13.94721714  1.86417116]
[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
